# Generated by Django 4.0.4 on 2023-02-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clientsystem_secret_clientsystem_password'),
        ('student', '0002_alter_studentworkreagents_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_works', to='clients.clientsystem', verbose_name='Преподаватель'),
        ),
    ]
